js:

  dmWidgetGalleryBackgroundPlugin:
    
    supersized:     supersized/slideshow/js/supersized.3.1.3
    bgnd:     bgnd/mb.bgndGallery
    view:      view
    form:      form

css:

  dmWidgetGalleryBackgroundPlugin:
    
    view:      view
    form:      form