js:

  dmWidgetGalleryBackgroundPlugin:
    
    supersized: supersized.3.2.7
    theme:      supersized.shutter
    view:       view
    form:       form

css:

  dmWidgetGalleryBackgroundPlugin:
    
    view:       view
    form:       form
    supersized: supersized
    theme:      supersized.shutter

